# Generated by Django 2.1 on 2019-03-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190322_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
