# Generated by Django 2.1 on 2019-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190322_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
