# Generated by Django 2.1 on 2019-03-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190322_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
