# Generated by Django 2.1 on 2019-03-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_noticeboard_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboard',
            name='user',
        ),
    ]
