# Generated by Django 2.1 on 2019-03-22 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_noticeboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
