# Generated by Django 2.1 on 2019-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_noticeboard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
