# Generated by Django 2.0.5 on 2019-03-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190323_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='url',
            field=models.URLField(default='', max_length=100),
        ),
    ]
