# Generated by Django 2.0.5 on 2019-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_noticeboard_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
