# Generated by Django 2.0.5 on 2019-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190329_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='url',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
