# Generated by Django 2.0.5 on 2019-04-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190329_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='notice',
            field=models.TextField(default='', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
