# Generated by Django 2.0.5 on 2019-04-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_noticeboard_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='docs',
            field=models.FileField(default='a', upload_to='docs'),
            preserve_default=False,
        ),
    ]
