# Generated by Django 2.0.5 on 2019-04-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_noticeboard_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='docs',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
    ]
