# Generated by Django 2.0.5 on 2019-06-05 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_a', models.TextField(default='', max_length=1000, unique=True)),
                ('date_a', models.DateTimeField(default=django.utils.timezone.now)),
                ('url_a', models.URLField(blank=True, max_length=100)),
                ('upvotes', models.IntegerField(default=0)),
                ('author_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_q', models.CharField(max_length=100, unique=True)),
                ('notice_q', models.TextField(default='', max_length=1000, unique=True)),
                ('date_q', models.DateTimeField(default=django.utils.timezone.now)),
                ('url_q', models.URLField(blank=True, max_length=100)),
                ('author_q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
