# Generated by Django 2.0.5 on 2019-06-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
    ]
