# Generated by Django 2.0.5 on 2019-06-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_ans',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='report_ans',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='report_ques',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='report_ques',
            name='report_id',
        ),
        migrations.DeleteModel(
            name='report_ans',
        ),
        migrations.DeleteModel(
            name='report_ques',
        ),
    ]
