# Generated by Django 2.2.3 on 2019-07-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190715_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='title_a',
            field=models.CharField(default='Hi', max_length=100, verbose_name='Title of Answer'),
            preserve_default=False,
        ),
    ]
