# Generated by Django 2.0.5 on 2019-06-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reportques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportques',
            name='reported_by',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportques',
            name='reported_q',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
