# Generated by Django 2.0.5 on 2019-06-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190623_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title_q',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title of Question'),
        ),
    ]
