# Generated by Django 2.2.3 on 2019-07-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reportques_reported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportans',
            name='report_count',
        ),
        migrations.RemoveField(
            model_name='reportques',
            name='report_count',
        ),
    ]
