# Generated by Django 2.0.5 on 2019-06-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190624_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportques',
            name='reported_by',
        ),
        migrations.AlterField(
            model_name='reportques',
            name='reported_q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
