# Generated by Django 2.0.5 on 2019-06-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190624_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_count', models.IntegerField(default=0)),
                ('reported_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
    ]
