# Generated by Django 2.0.5 on 2019-06-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reportans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportans',
            name='reported_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answer'),
        ),
    ]
